### ISSUE TITLE
坚果手机 Pro 3 的型号存在疑问

### ISSUE THREAD

**Issue by CainSakura** [xingrz/smartisan#1]
我买到的 12GB + 256GB 版本型号为 DT1901A，如下图
![图片](https://user-images.githubusercontent.com/16740801/68634312-f88fd900-052f-11ea-890e-0ac54998b152.png)

**Comment by CainSakura** [comment]
另经工信部考证，[DT1901A](http://www.tenaa.com.cn/WSFW/LicenceShow.aspx?code=Pxom3uuJQuIIGl%2b8ERY6iIutm2ElpIA77K6L7pQwJdLmWyNLJS%2fYSIm4txTQCly0) 与 [DT1902A](http://www.tenaa.com.cn/WSFW/LicenceShow.aspx?code=fWTl1%2fushgwBlQp4oHacw6UsKqc8cZk5X0hIyZ1tovRhhCy4zU68qu5BrNmSnYxe) 差别为机身后盖与摄像头排布区别，因此 DT1901A 应为黑色/松绿色，DT1902A 应为白色。

**Comment by xingrz** [comment]
![image](https://user-images.githubusercontent.com/288288/68635105-72c15d00-0532-11ea-8b71-981852f3e5f1.png)

这就很有趣了…

**Comment by xingrz** [comment]
![image](https://user-images.githubusercontent.com/288288/68635295-0eeb6400-0533-11ea-95a2-0e0adc88fe8a.png)

白8+256

**Comment by xingrz** [comment]
问了下朋友的黑8+128是DT1901A

**Comment by xingrz** [comment]
已修改。感谢。
