### ISSUE TITLE
能不能把历史版本列出来

### ISSUE THREAD

**Issue by aazmavethy** [xingrz/smartisan#2]
随着系统更新
有些机型不止越来越卡，想降级找不到低版本

**Comment by xingrz** [comment]
https://github.com/xingrz/smartisan/commits/master/_data/links.yml

**Comment by aazmavethy** [comment]
thanks！

XiNGRZ <notifications@github.com> 于2020年7月1日周三 上午11:16写道：

**Comment by xingrz** [comment]
> 有些机型不止越来越卡

心理作用而已。锤子的机器更新又不涉及系统层面。更新更新APK能卡到哪去。
